spring:
  application:
    name: logistics-service

server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
